AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    EnvironmentName:
      Type: String
    EnvironmentNumber:
      Type: String

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Fn::Sub: ${EnvironmentName}
      DefinitionBody:
        swagger: "2.0"
        info:
          title: 
            Fn::Sub: ${AWS::StackName}
        basePath: 
            Fn::Sub: "/${EnvironmentName}"
        schemes:
        - https
        paths:
          /:
            x-amazon-apigateway-any-method:
              produces:
              - application/json
              responses:
                "200":
                  description: 200 response
                  schema:
                    $ref: "#/definitions/Empty"
              security:
                - myApiUsers: []
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
              - application/json
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              responses: {}
              security:
                - myApiUsers: []
              x-amazon-apigateway-integration:
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
        x-amazon-apigateway-binary-media-types:
          - application/json
          - application/protobuf
        definitions:
          Empty:
            type: object
            title: Empty Schema
      Variables:
        LambdaFunctionName: !Ref Function
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      # For options see https://docs.aws.amazon.com/lambda/latest/dg/API_TracingConfig.html
      Tracing: Active
      Runtime: go1.x
      CodeUri: ./handler.zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
      Environment:   
        Variables:
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
          ENVIRONMENT_NUMBER:
            Ref: EnvironmentNumber
      Events:
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        ApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  URL:
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}"
  FunctionArn:
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"